language: elixir
elixir:
  - 1.5.2
otp_release:
  - 20.1
env:
  global:
    - MIX_ENV=test
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix do deps.get --only test, deps.compile
# before_script:
  # Set download location
  # - export PLT_FILENAME=elixir-${TRAVIS_ELIXIR_VERSION}_${TRAVIS_OTP_RELEASE}.plt
  # - export PLT_LOCATION=/home/travis/$PLT_FILENAME
  # Download PLT from danielberkompas/travis_elixir_plts on Github
  # Store in $PLT_LOCATION
  # - wget -O $PLT_LOCATION https://raw.github.com/danielberkompas/travis_elixir_plts/master/$PLT_FILENAME
script:
  - mix test
  - mix credo
  # - dialyzer --no_check_plt --plt $PLT_LOCATION --no_native _build/test/lib/fyyd_ex/ebin
after_script:
  - mix coveralls.travis
