language: elixir
elixir:
  - 1.5.2
otp_release:
  - 20.1
env:
  global:
    - MIX_ENV=test
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get --only test
after_script:
  - mix coveralls.travis
